included:
- Pym/App
- Pym/CheckIn
- Pym/Explorer
- Pym/Home
- Pym/Insights
- Pym/Onboarding
- Pym/PymCore
- Pym/Settings
excluded:
- Pym/PymCore/Sources/Generated

disabled_rules:
  - line_length
  - type_body_length