default_platform(:ios)

platform :ios do
  desc 'Runs all the tests'
  lane :test do
    scan(scheme: "Pym")
    slather(
      scheme: "Pym",
      proj: "Pym.xcodeproj",
      html: true,
      ignore: [
        "**/*.generated.swift"
      ]
    )
  end
end
